### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by Airon90** [trufae/fxos-app-sexturns#1]
Hi, I would like to translate your app into Italian and into Esperanto. How can I do that? Thank you very much!

**Comment by trufae** [comment]
I just did that change in config.js and config.html, so now, you only need to modify that lang.js to add the necessary strings for those new translations.

Thanks!

**Comment by Airon90** [comment]
Thank you very much! This is my pull request: https://github.com/trufae/fxos-app-sexturns/pull/3

**Comment by trufae** [comment]
thanks
