### ISSUE TITLE
People could have the same name

### ISSUE THREAD

**Issue by Airon90** [trufae/fxos-app-sexturns#5]
I'm not a coder, so I support some projects with translations.
I found the "err_noteq" variable: "Can't have the same name"

Two player could have the same name because this app can be used by lesbian or gay people, so it can be that two persons have the same name.

Is it possible to remove support to such function? Thank you

**Comment by trufae** [comment]
The game identifies each player with a different name, I didn't implied any genre connotation with that error message. It's just a practical way to identify who's going to play, and if two users have the same name it is not possible to determine who is who.

**Comment by Airon90** [comment]
Ops, you're right. I didn't realize that. Sorry
